/**
 * Single source of truth for terminology. Every <InfoTip> and <Term>
 * reads from here, and /glossary renders the full list.
 */

export type GlossaryCategory =
  | "Admissions"
  | "Test scores"
  | "Students & access"
  | "Cost & outcomes"
  | "School types"
  | "How we measure"
  | "Data sources";

export interface GlossaryEntry {
  term: string;
  /** One or two sentences, shown in the pop-over. */
  short: string;
  /** Longer explanation for the glossary page. */
  long?: string;
  /** "Why it matters" framing for students. */
  why?: string;
  category: GlossaryCategory;
  /** Keys of related entries (validated at render time via isTermKey). */
  related?: string[];
}

export const GLOSSARY_CATEGORIES: GlossaryCategory[] = [
  "Admissions",
  "Test scores",
  "Students & access",
  "Cost & outcomes",
  "School types",
  "How we measure",
  "Data sources",
];

const entries = {
  "acceptance-rate": {
    term: "Acceptance rate",
    short: "The share of applicants who were offered admission. Lower means harder to get in.",
    long: "Calculated as admitted ÷ applicants for a single admissions cycle. A 5% acceptance rate means roughly 1 in 20 applicants was admitted.",
    why: "It's the quickest signal of how competitive admission is, but it says nothing about fit, cost, or outcomes. Schools with many applicants can look more selective than they are for a well-prepared student.",
    category: "Admissions",
    related: ["applicants", "admitted", "selectivity"],
  },
  "admission-factor": {
    term: "Admission factors",
    short: "What a college looks at when deciding: whether each item, like GPA or an essay, is required, considered, or not considered at all.",
    long: "Colleges report these to the federal government each year. \"Considered\" means it can help but isn't required. \"Not considered\" means the college doesn't use it, even if you send it.",
    why: "It tells you where to spend your effort: a required essay matters; a factor that isn't considered won't change the decision.",
    category: "Admissions",
    related: ["legacy-status", "secondary-school-record", "test-policy"],
  },
  "legacy-status": {
    term: "Legacy status",
    short: "Whether an applicant's parent (or other relative) attended the college. Some colleges consider it in admission; many have stopped.",
    category: "Admissions",
    related: ["admission-factor"],
  },
  "secondary-school-record": {
    term: "High school record",
    short: "The courses a student took in high school and how challenging they were, as shown on the transcript, beyond the GPA alone.",
    category: "Admissions",
    related: ["admission-factor", "college-prep-program"],
  },
  "college-prep-program": {
    term: "College-prep program",
    short: "Finishing a set of high school courses that prepare students for college, such as several years of math, science, English, and a language.",
    category: "Admissions",
    related: ["secondary-school-record"],
  },
  "admit-rate-by-sex": {
    term: "Acceptance rate by sex",
    short: "The share of men who applied who were admitted, and the same for women, as colleges report them to the federal government.",
    long: "Applicants who reported another gender or none count in the overall rate but aren't shown as a separate rate: the numbers are too small. A gap is compared only when both men and women number at least 200 applicants.",
    why: "At some colleges one sex applies in much larger numbers than the other. A gap can reflect who applies as much as how the college chooses; the numbers alone don't say which.",
    category: "Admissions",
    related: ["acceptance-rate", "gender-balance"],
  },
  applicants: {
    term: "Applicants",
    short: "The number of first-year students who submitted a completed application.",
    category: "Admissions",
    related: ["acceptance-rate", "admitted"],
  },
  admitted: {
    term: "Admitted",
    short: "Applicants who received an offer of admission.",
    category: "Admissions",
    related: ["applicants", "enrolled", "yield"],
  },
  enrolled: {
    term: "Enrolled",
    short: "Admitted students who actually showed up and started classes that fall.",
    category: "Admissions",
    related: ["admitted", "yield"],
  },
  yield: {
    term: "Yield rate",
    short: "The share of admitted students who choose to enroll. High yield means students who get in tend to say yes.",
    long: "Calculated as enrolled ÷ admitted. Yield is often read as a signal of how much students want to attend once they have the offer.",
    why: "A high yield often reflects strong demand or many binding Early Decision admits. Low yield can mean the school is frequently a backup choice.",
    category: "Admissions",
    related: ["admitted", "enrolled"],
  },
  "open-admission": {
    term: "Open admission",
    short: "A policy of admitting essentially anyone with a high school diploma or equivalent. These colleges don't report an acceptance rate or test scores.",
    category: "Admissions",
    related: ["acceptance-rate"],
  },
  selectivity: {
    term: "Selectivity tier",
    short: "Our plain-English label for acceptance rate: Most selective (<10%), Highly selective (10–25%), Selective (25–50%), Broadly accessible (50%+).",
    category: "How we measure",
    related: ["acceptance-rate"],
  },
  "median-vs-midpoint": {
    term: "Median vs. midpoint",
    short: "The median is the score in the middle of all enrolled students who submitted one. The midpoint is halfway between the 25th and 75th percentiles.",
    long: "Colleges only recently began reporting true medians to the federal government, so older years have the midpoint alone. When scores bunch up near the top of the range, the median sits above the midpoint. The SAT total median here adds the two section medians, an approximation like the SAT total range.",
    why: "The median says where the typical student actually scored; the midpoint is only the center of the range.",
    category: "Test scores",
    related: ["middle-50", "percentile"],
  },
  "middle-50": {
    term: "Middle 50%",
    short: "The range between the 25th and 75th percentile scores of enrolled students. Half of students scored inside it.",
    long: "If a school's SAT middle 50% is 1400–1520, a quarter of enrolled students scored 1400 or below and a quarter scored 1520 or above.",
    why: "Landing inside the range means your score is typical for the school. Being below the 25th percentile doesn't rule you out; a quarter of students are there too.",
    category: "Test scores",
    related: ["percentile", "sat", "act", "test-submission"],
  },
  percentile: {
    term: "25th / 75th percentile",
    short: "The 25th percentile is the score that 25% of students scored at or below; the 75th percentile is the score 75% scored at or below.",
    category: "Test scores",
    related: ["middle-50"],
  },
  sat: {
    term: "SAT total",
    short: "The College Board's admissions test, scored 400–1600: Reading & Writing (200–800) plus Math (200–800).",
    long: "Where a college's own Common Data Set reports its SAT total percentiles, we show those. Elsewhere we estimate the total range by adding the Reading & Writing and Math percentiles, an approximation because the same student isn't always at the 25th percentile in both sections. Rankings always use the added sections, so every college is measured the same way.",
    category: "Test scores",
    related: ["sat-ebrw", "sat-math", "middle-50", "act"],
  },
  "sat-ebrw": {
    term: "SAT Reading & Writing",
    short: "The Evidence-Based Reading and Writing section of the SAT, scored 200–800.",
    category: "Test scores",
    related: ["sat", "sat-math"],
  },
  "sat-math": {
    term: "SAT Math",
    short: "The Math section of the SAT, scored 200–800.",
    category: "Test scores",
    related: ["sat", "sat-ebrw"],
  },
  act: {
    term: "ACT composite",
    short: "The ACT's overall score, from 1 to 36, averaging English, Math, Reading, and Science.",
    long: "From 2025 the enhanced ACT makes the Science section optional and computes the composite from English, Math, and Reading alone, so composites from newer classes may mix both kinds of scores.",
    category: "Test scores",
    related: ["sat", "middle-50"],
  },
  "test-optional": {
    term: "Test-optional",
    short: "A policy that lets applicants decide whether to submit SAT/ACT scores. Students who don't submit aren't penalized.",
    why: "At test-optional schools, reported score ranges only describe students who chose to submit, and those students usually scored higher.",
    category: "Test scores",
    related: ["test-submission", "middle-50"],
  },
  "test-policy": {
    term: "Test policy",
    short: "How a college uses SAT/ACT scores: required, required for some applicants, recommended, considered if submitted (test-optional), or not considered at all (test-blind).",
    long: "Federal data gives the policy for students who already enrolled. Where a college's Common Data Set states its policy for the coming application cycle, we show that instead, and its source names the cycle.",
    why: "At test-blind schools (like the University of California) you won't see score ranges, because scores aren't collected.",
    category: "Test scores",
    related: ["test-optional", "test-submission", "application-cycle", "required-for-some"],
  },
  "test-submission": {
    term: "Test submission rate",
    short: "The share of enrolled students who submitted a given test score. Below 50%, the reported range may not represent the whole class.",
    long: "A college's Common Data Set also gives how many students sent each test, shown with the share where it's reported.",
    category: "Test scores",
    related: ["test-optional", "middle-50"],
  },
  "undergrad-enrollment": {
    term: "Undergraduate enrollment",
    short: "The total number of degree-seeking undergraduate students (not counting graduate students).",
    why: "Size shapes everyday life: class sizes, how many clubs there are, research opportunities, and how easy it is to find your people.",
    category: "Students & access",
    related: ["size-tier"],
  },
  "size-tier": {
    term: "Size tier",
    short: "Our grouping by undergrad count: Small (<5K), Medium (5–15K), Large (15–30K), Very large (30K+).",
    category: "How we measure",
    related: ["undergrad-enrollment"],
  },
  "pell-grant": {
    term: "Pell Grant",
    short: "A federal grant for undergraduates with significant financial need. The share of Pell recipients is a common measure of economic diversity.",
    long: "Pell Grants don't need to be repaid. Most recipients come from families earning under about $60,000 a year.",
    why: "A higher Pell share suggests a school enrolls and supports more lower-income students.",
    category: "Students & access",
    related: ["first-gen"],
  },
  "first-gen": {
    term: "First-generation student",
    short: "A student whose parents did not complete a four-year college degree.",
    why: "Schools with more first-gen students often have stronger support networks for navigating college for the first time.",
    category: "Students & access",
    related: ["pell-grant"],
  },
  "gender-balance": {
    term: "Men and women",
    short: "The share of degree-seeking undergraduates who are men and who are women, as colleges report them to the federal government.",
    why: "Nationally, more women than men attend four-year colleges, so a campus near 50/50 is less common than it sounds.",
    category: "Students & access",
    related: ["degree-seeking", "undergrad-enrollment", "another-gender"],
  },
  "another-gender": {
    term: "Another gender",
    short: "Students whose college records hold a gender other than man or woman, such as nonbinary. Colleges could report this count to the federal government for a few years; it was optional, and most didn't.",
    long: "It doesn't count transgender students overall (a trans woman is counted as a woman), and it says nothing about sexual orientation. A blank means the college didn't collect it; 0 can mean the college doesn't record other genders rather than that no one does. Colleges that collect it left the cells blank when any count was under 5, and we show counts under 10 as \"fewer than 10\". Colleges record gender so differently that a higher number mostly reflects record-keeping, so we never rank or compare colleges by it. The federal survey has since stopped asking for it, so the newest count is the last one.",
    why: "The federal men and women shares always add up to 100%, because colleges assign students of another or unknown gender to one of the two. This count is the only official figure beside them.",
    category: "Students & access",
    related: ["gender-balance", "gender-unknown"],
  },
  "gender-unknown": {
    term: "Gender unknown",
    short: "Students whose gender the college doesn't know, for example because they didn't answer. Every college reports this count, separately from another gender.",
    long: "Like students of another gender, they're assigned to men or women in the federal shares. We show counts under 10 as \"fewer than 10\".",
    category: "Students & access",
    related: ["another-gender", "gender-balance"],
  },
  "state-law-public-colleges": {
    term: "State law on public colleges",
    short: "A state statute that limits what public colleges in that state may offer, such as offices or programs designed around identity. It applies to public colleges only; private colleges in the state aren't covered.",
    long: "We show the statute, the date it took effect, and a one-line summary we checked against the statute's text, with a link to it. Some laws name sexual orientation or gender identity; others ban diversity, equity, and inclusion offices in general terms, and the summary says when a law doesn't name them. A law can close an office a college once had: UT Austin's Gender and Sexuality Center closed in 2024 under Texas SB 17. Student groups are often exempt, so a law doesn't mean there's no LGBTQ+ community on campus.",
    category: "Students & access",
    related: ["another-gender"],
  },
  "lgbtq-resource-center": {
    term: "LGBTQ+ resource center",
    short: "A campus office or staffed program (at least half a full-time position, by the Consortium of Higher Education LGBT Resource Professionals' own criteria) serving LGBTQ+ students.",
    long: "We show a center the Consortium's own list credits, dated to when we read that list. Directories lag closures: a state law can close a center after the list was last updated (UT Austin's Gender and Sexuality Center, closed 2024 under Texas SB 17), so a listed center isn't a claim that it's still open, especially at a public college in a state with such a law.",
    category: "Students & access",
    related: ["national-directory", "state-law-public-colleges"],
  },
  "trans-policy-clearinghouse": {
    term: "Trans Policy Clearinghouse",
    short: "Seven lists of colleges, by policy, that Dr. Genny Beemyn keeps independently (gennyb.com): nondiscrimination, gender-inclusive housing and restrooms, chosen name and pronouns, student health coverage, trans-inclusive athletics, and trans admission at historically women's and men's colleges.",
    long: "Formerly hosted by Campus Pride, kept independently since 2023. Each list gives names only, matched to a college here by name, city, and state; a listing is a lead the list's author found, not something we've confirmed with the college, so it's shown with the organization's name, the list's link, and the date we read it — never a plain “yes.” A college missing from a list isn't shown as a “no”: the list may simply not have found it yet.",
    category: "Students & access",
    related: ["gender-inclusive-housing", "chosen-name-policy", "nondiscrimination-policy", "national-directory"],
  },
  "gender-inclusive-housing": {
    term: "Gender-inclusive housing",
    short: "Campus housing where students can choose to share a room or suite with people of any gender, regardless of sex or gender identity.",
    why: "It lets trans, nonbinary, and other students choose roommates without being assigned by sex.",
    category: "Students & access",
    related: ["trans-policy-clearinghouse", "chosen-name-policy"],
  },
  "chosen-name-policy": {
    term: "Chosen name and pronouns on campus records",
    short: "Whether a college lets students use a name and pronouns other than their legal ones on campus systems (ID cards, class rosters, email), without a legal name change.",
    category: "Students & access",
    related: ["trans-policy-clearinghouse", "gender-inclusive-housing"],
  },
  "nondiscrimination-policy": {
    term: "Nondiscrimination policy",
    short: "The college's own statement of who its nondiscrimination policy protects. We show whether it names gender identity or expression; some policies also name sexual orientation.",
    long: "Most colleges, public and private, include sexual orientation and gender identity today, but a policy's exact wording (and whether it's enforceable, versus aspirational) varies, and a college can narrow or drop protections it once had.",
    category: "Students & access",
    related: ["trans-policy-clearinghouse", "lgbtq-resource-center"],
  },
  "part-time-student": {
    term: "Part-time student",
    short: "An undergraduate taking fewer credits than a full course load, usually under 12 credit hours a term.",
    why: "Where many students study part-time, often while working, campus life and class schedules look different from a mostly full-time college.",
    category: "Students & access",
    related: ["degree-seeking", "adult-students"],
  },
  "adult-students": {
    term: "Students 25 and older",
    short: "The share of undergraduates aged 25 or older. The federal survey asks about age every other fall, so this figure is a year older than enrollment.",
    why: "A high share usually means many students are returning to college or working while they study, so classes and services are built around them.",
    category: "Students & access",
    related: ["part-time-student"],
  },
  // Where first-years come from (specs/data-expansion/residence.md).
  // Transfers in (specs/data-expansion/transfers.md).
  "transfer-in": {
    term: "Transfer student (transfer-in)",
    short: "An undergraduate who enrolled this fall after attending another college. The share is transfer-ins divided by all new undergraduates: transfer-ins plus first-time students.",
    long: "From the federal Fall Enrollment survey, which counts new transfer-ins every fall, full-time and part-time. Transfers out are a different measure: the 8-year outcomes show how many of an entering class left and enrolled at another college. No federal data counts students leaving in a given year.",
    why: "A large transfer share means the college admits and plans for transfer students; a small one may mean few transfer seats.",
    category: "Students & access",
    related: ["transfer-out", "first-time-student", "outcome-measures"],
  },
  "in-state-student": {
    term: "In-state, out-of-state, and international students",
    short: "Where a first-year lived when they applied: the college's own state, another U.S. state, DC, or territory (out-of-state), or another country (international). Shares here are of every first-year, including the few whose residence wasn't reported.",
    long: "Colleges report each first-year's home state to the federal government every fall; reporting is required in even-numbered years and optional in odd ones, so the site uses even years. A Common Data Set's \"percent from out of state\" leaves international students out of both the count and the total, so it reads higher than the out-of-state share here. The share of first-years from out of state is not the same as the out-of-state acceptance rate, which counts who got in, not who came.",
    why: "A college that draws mostly from its own state feels different from one with students from across the country, and at a public university, out-of-state students usually pay a higher tuition.",
    category: "Students & access",
    related: ["first-time-student", "in-state-tuition"],
  },
  "first-time-student": {
    term: "First-time student",
    short: "A student starting college for the first time (usually right after high school), as opposed to a transfer student. The federal \"first-years\" counted for residence are first-time students seeking a degree or certificate.",
    category: "Students & access",
    related: ["in-state-student", "degree-seeking"],
  },
  "degree-seeking": {
    term: "Degree-seeking undergraduate",
    short: "A student enrolled toward a bachelor's or associate degree, as opposed to someone taking classes without pursuing a degree. The site's undergraduate counts and shares include only degree-seeking students.",
    long: "The newest figure may come from the college's own Common Data Set, a year newer than federal data; the ⓘ shows which.",
    category: "Students & access",
    related: ["undergrad-enrollment"],
  },
  "race-ethnicity": {
    term: "Race/ethnicity breakdown",
    short: "The share of undergraduates in each federal reporting category. International students are counted separately regardless of race.",
    category: "Students & access",
    related: ["diversity-index"],
  },
  "diversity-index": {
    term: "Diversity index",
    short: "The chance that two randomly chosen students are from different racial/ethnic groups. 0 = everyone is the same; closer to 1 = more mixed.",
    long: "We use Simpson's diversity index: 1 − Σ(share²) over all reported categories. It rewards both more groups and more even balance between them.",
    category: "How we measure",
    related: ["race-ethnicity"],
  },
  "average-cost": {
    term: "Average cost (all students)",
    short: "Our estimate of what the average first-year actually paid in a year for everything: tuition and fees, housing, food, books, and other expenses, after grants. Students with grants pay the full price minus their grant; students without grants pay the full price.",
    long: "Calculated from same-year federal data: the sticker price (tuition and fees for each student's residency rate, plus books, on-campus room and board, and other expenses), weighted by the share of first-years paying each rate, minus the share who received grants times their average grant. Loans aren't subtracted, since they're still paid back.",
    why: "Published \"average net price\" figures only cover students who got aid, so they understate what a typical student pays, often by tens of thousands of dollars at colleges where many students pay full price. It assumes on-campus living, so it runs high at commuter-heavy schools.",
    category: "Cost & outcomes",
    related: ["net-price", "cost-of-attendance", "in-state-tuition", "grant-aid"],
  },
  "aid-generosity": {
    term: "Aid generosity",
    short: "How much of the full price (tuition, housing, food, books and other costs) grants cover, averaged over every first-year, counting students who get no grants as 0%.",
    long: "Calculated as total grant dollars ÷ number of first-years ÷ full price. Tiers: Very generous (55%+), Generous (40–55%), Moderate (25–40%), Limited (under 25%). It's similar to the \"tuition discount rate\" colleges track, but measured against the full cost of attendance.",
    why: "Two colleges with the same sticker price can cost very different amounts. At generous colleges the sticker price overstates what most students pay; at colleges with limited aid, most students pay close to it.",
    category: "Cost & outcomes",
    related: ["average-cost", "grant-aid", "cost-of-attendance", "need-met"],
  },
  "in-state-tuition": {
    term: "In-state vs. out-of-state tuition",
    short: "Public universities charge state residents a lower rate, often half or less of what out-of-state students pay. Some also have an in-district rate for local residents.",
    category: "Cost & outcomes",
    related: ["average-cost", "cost-of-attendance"],
  },
  "net-price": {
    term: "Net price",
    short: "What a student actually pays per year after grants and scholarships: tuition, fees, housing, and books minus gift aid. Loans are not subtracted. The average covers only students who received grants.",
    long: "The average net price shown is for first-time, full-time students who received grant or scholarship aid, as reported to the federal government. Students who got no grants aren't included, so full-paying families pay more than the average. At public colleges it covers in-state students only.",
    why: "It's usually far below the sticker price, especially at wealthy private colleges with generous aid. Every college has a net price calculator for your family's exact estimate.",
    category: "Cost & outcomes",
    related: ["cost-of-attendance", "net-price-by-income"],
  },
  "cost-of-attendance": {
    term: "Cost of attendance (sticker price)",
    short: "The full published price of a year: tuition, fees, housing, food, books, and other expenses, before any financial aid.",
    why: "Few students pay this; compare it with net price to see how much aid typically covers.",
    category: "Cost & outcomes",
    related: ["net-price"],
  },
  "net-price-by-income": {
    term: "Net price by family income",
    short: "Average net price by family income ($0–30K up to $110K+) for students receiving federal (Title IV) aid, meaning those who filed the FAFSA and received federal grants or loans. Shows how much a college's aid depends on need.",
    why: "At colleges with strong need-based aid, lower-income families can pay far less than the average net price.",
    category: "Cost & outcomes",
    related: ["net-price", "pell-grant"],
  },
  "median-earnings": {
    term: "Median earnings",
    short: "The middle salary of former students 10 years after they first enrolled, whether or not they graduated. Covers students who received federal financial aid.",
    why: "Earnings reflect majors, location, and who enrolls as much as the college itself, so treat big gaps as clues rather than cause and effect.",
    category: "Cost & outcomes",
    related: ["payback", "graduation-rate", "earnings-after-completion"],
  },
  // Field of study earnings and debt (specs/data-expansion/field-of-study.md).
  "field-of-study": {
    term: "Field of study",
    short: "A specific major, grouped by its 4-digit CIP code (the federal classification of academic fields), at one credential level. The site shows bachelor's fields only.",
    long: "Earnings and debt here are measured per field of study and credential level at each college, not per college overall, so a college's typical graduate and its computer science graduate can look very different.",
    category: "Cost & outcomes",
    related: ["earnings-after-completion"],
  },
  "earnings-after-completion": {
    term: "Earnings after completion",
    short: "Median pay for graduates of one field at one college, counted from when they completed that credential — not from when they started, the way the site's college-wide earnings figure is. One and four years after completion are shown, plus the national median in the same field for comparison.",
    long: "Because it's measured from completion rather than entry, and only among graduates who worked and weren't still enrolled, it isn't directly comparable to the college-wide \"median earnings\" figure, which includes students who never finished. The 1-year, 4-year, and Pell/non-Pell figures can also come from different graduating classes a few years apart — each is the latest the Department of Education has calculated for it.",
    why: "Two colleges' overall earnings can differ mainly because of what students major in; comparing the same field narrows that out.",
    category: "Cost & outcomes",
    related: ["median-earnings", "field-of-study"],
  },
  "graduation-rate": {
    term: "Graduation rate",
    short: "The share of full-time, first-time students who finish within 150% of normal time: six years for a four-year degree.",
    category: "Cost & outcomes",
    related: ["retention-rate"],
  },
  // Outcome Measures (specs/data-expansion/outcome-measures.md).
  // Time to degree (specs/data-expansion/time-to-degree.md).
  "time-to-degree": {
    term: "Time to degree (within 4, 6, 8 years)",
    short: "Of the students who started at a college, the share who earned a degree or certificate there within 4, 6, and 8 years. The shares add up over time: a student who finished in 4 years is counted at 6 and 8 too.",
    long: "From the federal Outcome Measures survey, which follows every entering student, including part-time and transfer students. For a transfer student the clock starts when they arrive at this college, not when they first started college. The newest group entered about 8 years before the data's release, so all three numbers describe the same students.",
    why: "Four years of tuition is the plan for most families; each extra year adds cost. The gap between the 4- and 6-year shares shows how many students need longer.",
    category: "Cost & outcomes",
    related: ["outcome-measures", "graduation-rate"],
  },
  "outcome-measures": {
    term: "8-year outcomes (Outcome Measures)",
    short: "What happened to everyone who started at a college, 8 years later: earned a degree or certificate there, still enrolled, enrolled at another college, or no record. Counts transfer students and part-timers, not just first-time, full-time students.",
    long: "From the federal Outcome Measures survey. Unlike the graduation rate, which follows only first-time, full-time students and counts a transfer out as not finishing, it follows every entering student, says how many went on to another college, and gives 8 years to finish. The newest group entered about 8 years before the data's release.",
    why: "Fairer to colleges with many transfer, part-time, or adult students, and it shows whether students who leave keep going somewhere else.",
    category: "Cost & outcomes",
    related: ["graduation-rate", "transfer-out", "adjusted-cohort"],
  },
  "transfer-out": {
    term: "Transfer-out (enrolled elsewhere)",
    short: "Students who left without a degree or certificate and enrolled at another college. Outcome Measures counts them 8 years after entry, using enrollment records from the National Student Clearinghouse.",
    long: "It says where students enrolled, not whether they finished there. Some colleges are a planned first stop (students start, then transfer to finish), so a high share isn't always a bad sign.",
    category: "Cost & outcomes",
    related: ["outcome-measures", "graduation-rate"],
  },
  // Graduation by group (specs/data-expansion/graduation-by-group.md).
  "pell-graduation-gap": {
    term: "Pell graduation gap",
    short: "How many points lower the 6-year graduation rate is for Pell Grant recipients than for students who got neither a Pell Grant nor a subsidized federal loan, in the same entering class.",
    long: "Federal data splits each entering class of first-time, full-time students three ways: Pell Grant recipients, students with a subsidized federal loan but no Pell Grant, and students with neither. Comparing Pell recipients with the \"neither\" group compares lower-income students with students who didn't qualify for need-based federal aid. A negative gap means Pell recipients graduated more often. Groups under 30 students aren't shown. The newest figure may come from the college's own Common Data Set, a year newer than federal data; the ⓘ shows which.",
    why: "Colleges admit students from every income level; the gap shows whether lower-income students who enroll finish as often as everyone else. It says more about support than the overall rate does.",
    category: "Cost & outcomes",
    related: ["graduation-rate", "pell-grant", "adjusted-cohort", "on-time-graduation"],
  },
  // CDS student body and outcomes (specs/data-expansion/cds-student-body-and-outcomes.md).
  "on-time-graduation": {
    term: "Finished within 4 years",
    short: "First-time, full-time students who started a bachelor's degree; the college's own count from its Common Data Set. The 6-year rate counts the same students two years later.",
    long: "Colleges that publish a Common Data Set report how many of each entering class finished within 4, 5, and 6 years, split by Pell Grant recipients, students with a subsidized federal loan but no Pell Grant, and students with neither. Groups under 30 students aren't shown. This is a different group from the \"Time to degree\" figures, which follow every entering student, including part-time and transfer students.",
    why: "Four years of tuition is the plan for most families; the gap between the 4- and 6-year marks shows how many students need longer, and whether that differs for lower-income students.",
    category: "Cost & outcomes",
    related: ["pell-graduation-gap", "time-to-degree", "cds"],
  },
  "adjusted-cohort": {
    term: "Adjusted cohort",
    short: "The students a graduation or outcome rate follows, minus those who left for allowed reasons (military service, a religious mission, foreign aid service, death or permanent disability). Rates are shares of it.",
    long: "We don't show a group's rate when its adjusted cohort has fewer than 30 students: a few students would swing it by many points (the rule the College Scorecard uses).",
    category: "How we measure",
    related: ["graduation-rate", "outcome-measures", "pell-graduation-gap"],
  },
  "retention-rate": {
    term: "Retention rate",
    short: "The share of full-time first-year students who come back for their second year. An early signal of student satisfaction and support.",
    long: "The newest figure may come from the college's own Common Data Set, a year newer than federal data; the ⓘ shows which.",
    category: "Cost & outcomes",
    related: ["graduation-rate"],
  },
  "median-debt": {
    term: "Median debt",
    short: "The middle amount of federal student loans owed by graduates when they finish. Private loans and parent PLUS loans aren't included.",
    why: "The monthly payment shown assumes a standard 10-year repayment plan.",
    category: "Cost & outcomes",
    related: ["net-price", "payback", "federal-loan-rate"],
  },
  locale: {
    term: "Setting (city, suburb, town, rural)",
    short: "Where the campus sits, using the federal government's locale codes: a city, a suburb, a town, or a rural area, each split by size or distance.",
    long: "\"Town: Remote\" means a town more than 35 miles from a city; \"Rural: Fringe\" is countryside within about 5 miles of a city.",
    category: "School types",
    related: ["carnegie-classification"],
  },
  "carnegie-classification": {
    term: "Carnegie Classification",
    short: "A standard way to group U.S. colleges by what they do: the mix of degrees they award, their size, how much research they do, and more. The 2025 edition is the newest.",
    category: "School types",
    related: ["r1", "student-access-and-earnings"],
  },
  r1: {
    term: "R1, R2 (research universities)",
    short: "Carnegie's research designations. R1 universities spend the most on research and award the most research doctorates; R2 is the next tier.",
    why: "Research universities offer chances to join faculty research, but classes can be larger and some teaching falls to graduate students.",
    category: "School types",
    related: ["carnegie-classification"],
  },
  "student-access-and-earnings": {
    term: "Student Access and Earnings",
    short: "A 2025 Carnegie grouping of colleges by how well they enroll students from their area's lower-income families (access) and what graduates later earn (earnings).",
    long: "\"Opportunity Colleges and Universities\" pair higher access with higher earnings. This is Carnegie's label, shown as reported, not the site's verdict.",
    category: "School types",
    related: ["carnegie-classification", "pell-grant"],
  },
  hbcu: {
    term: "HBCU",
    short: "A Historically Black College or University: founded before 1964 with the mission of educating Black Americans, and recognized as such under federal law.",
    category: "School types",
    related: ["hsi"],
  },
  hsi: {
    term: "Hispanic-Serving and other minority-serving institutions",
    short: "Colleges eligible for federal funding because many of their students are from a particular group, such as Hispanic-Serving Institutions, where at least a quarter of undergraduates are Hispanic.",
    long: "Eligibility is recalculated each year from enrollment, so a college can gain or lose a designation. The site shows the College Scorecard's flags.",
    category: "School types",
    related: ["hbcu", "tribal-college"],
  },
  "single-sex": {
    term: "Women's and men's colleges",
    short: "Colleges that admit only women or only men to their undergraduate programs. Many men's colleges are religious seminaries.",
    category: "School types",
    related: ["hsi"],
  },
  "tribal-college": {
    term: "Tribal college",
    short: "A college chartered by a Native American tribe or the federal government to serve Native students and communities.",
    category: "School types",
    related: ["hsi"],
  },
  "land-grant": {
    term: "Land-grant university",
    short: "A college designated by its state to receive federal support under the Morrill Acts, originally to teach agriculture, engineering, and the practical sciences. Every state has at least one.",
    category: "School types",
    related: ["carnegie-classification"],
  },
  "cip-code": {
    term: "Field of study (CIP code)",
    short: "The federal code for a field of study, from the Classification of Instructional Programs (CIP 2020). A 6-digit code is one program (11.0701, Computer Science); its first 2 digits are the broad field (11, Computer and Information Sciences).",
    long: "Colleges report every degree they award under one of about 2,200 program codes. The site shows programs by their federal names, which can differ from what a college calls its major, and groups them into about 40 broad fields for comparisons and trends. NCES revises the codes about once a decade; the 2020 edition replaced CIP 2010 starting with the 2020 completions file, and older years are read through NCES's crosswalk.",
    why: "A college can teach a subject under a differently named program (\"Economics\" vs. \"Econometrics and Quantitative Economics\"), so search the full list for a few names before ruling a college out.",
    category: "How we measure",
    related: ["first-major", "second-major"],
  },
  "first-major": {
    term: "First major",
    short: "A graduate's primary major. Every bachelor's degree has exactly one, so first majors add up to the college's bachelor's degrees, and the site's shares of graduates use them.",
    long: "From the federal Completions survey: degrees awarded from July through June, by program. A double major counts once here under the first major and again as a second major.",
    why: "The share of graduates in a major tells you how central it is to the college: how many classmates, courses, and faculty to expect.",
    category: "Students & access",
    related: ["second-major", "cip-code"],
  },
  "second-major": {
    term: "Second major",
    short: "A double major's other field. Counted separately from first majors, so adding them would count some graduates twice.",
    long: "Colleges report second majors only for graduates who completed two majors in one degree. Second-major counts show what students pair with their main field (math and economics are common second majors).",
    category: "Students & access",
    related: ["first-major", "cip-code"],
  },
  "student-faculty-ratio": {
    term: "Student-to-faculty ratio",
    short: "Full-time-equivalent undergraduates and graduate students for each full-time-equivalent instructional faculty member, not counting faculty who teach only graduate or professional students. Written \"8 to 1\".",
    long: "It is not the average class size: a college with a low ratio can still have large lecture courses, and faculty time also goes to research and advising. Colleges compute it themselves, so definitions vary, for example in whether research faculty count.",
    why: "A rough signal of how much faculty attention there is to go around. For class sizes, look at a college's Common Data Set (section I).",
    category: "Students & access",
  },
  "full-time-faculty": {
    term: "Full-time faculty share",
    short: "The share of a college's faculty who work full-time, rather than part-time or adjunct (College Scorecard, from IPEDS Human Resources data).",
    long: "Nationally the full-time share has drifted down for years as colleges lean more on part-time and adjunct instructors. A high share doesn't guarantee small classes or more office hours, but it's a rough proxy for how much of the teaching is done by faculty with an ongoing stake in the college.",
    why: "A clue to how much of the teaching load falls to instructors who are only there part-time.",
    category: "Students & access",
    related: ["student-faculty-ratio", "instructional-staff"],
  },
  "instructional-staff": {
    term: "Instructional staff",
    short: "Everyone IPEDS counts as teaching staff at a college: professors, lecturers, and other faculty, across every academic rank.",
    why: "It's the group the faculty salary and full-time-faculty figures describe, which is broader than just tenure-track professors.",
    category: "Students & access",
    related: ["nine-month-equated-salary"],
  },
  "nine-month-equated-salary": {
    term: "9-month equated salary",
    short: "Average instructional staff salary (all ranks combined), converted to what it would be on a standard 9-month academic-year contract (IPEDS Salaries survey).",
    long: "Faculty on 10-, 11-, or 12-month contracts have their pay scaled down to a 9-month equivalent, so colleges with different contract lengths can be compared on the same basis. This is a different figure from College Scorecard's faculty salary field, which is a plain monthly average and isn't equated the same way — the two shouldn't be mixed.",
    why: "Pay varies enormously with local cost of living: a salary that goes far in a small Midwestern town may barely cover rent near a coastal city. Compare it with care, and expect it to track an area's cost of living as much as a college's generosity.",
    category: "Students & access",
    related: ["instructional-staff"],
  },
  endowment: {
    term: "Endowment",
    short: "Invested assets a college holds and spends from over time, not its yearly budget. Shown per student (per FTE), since a bigger college needs a bigger endowment to offer the same per-student spending.",
    long: "Reported at year end on the college's own accounting form, so figures are never compared between public and private colleges (see GASB vs. FASB). Many public universities' endowments sit mostly in a separate, legally distinct foundation that this survey doesn't count, so a public college's reported endowment usually understates what's actually available to it.",
    why: "A rough sense of a college's financial cushion: more endowment per student generally means more capacity for aid and programs that don't depend on tuition each year.",
    category: "Cost & outcomes",
    related: ["gasb-fasb", "fte-student"],
  },
  "instruction-expenses": {
    term: "Instruction spending per student",
    short: "What a college spent on instruction (faculty salaries, academic departments) in a fiscal year, divided by full-time-equivalent (FTE) students. Not the sticker price or what any one student pays.",
    long: "Reported on the college's own accounting form (GASB for public, FASB for private nonprofit), so it's compared only within the same form. A high number can mean small classes and well-paid faculty, or it can mean a college with many costly graduate and research programs spread over a modest undergraduate population.",
    why: "One proxy for how much a college invests in teaching, per student, though it says nothing about teaching quality directly.",
    category: "Cost & outcomes",
    related: ["gasb-fasb", "fte-student", "student-faculty-ratio"],
  },
  "gasb-fasb": {
    term: "GASB vs. FASB accounting",
    short: "The two accounting standards colleges use to report finances to the federal government: GASB (public colleges) and FASB (private nonprofit colleges). For-profit colleges use a third form. The three categorize revenue and expenses differently, so figures are never compared across them.",
    long: "This is why the site always says \"more than other public colleges\" or \"other private nonprofit colleges\", never a single national ranking for endowment or spending per student.",
    why: "Explains why a public and a private college's reported endowment or instruction spending can look very different even when the underlying finances are similar.",
    category: "Cost & outcomes",
    related: ["endowment", "instruction-expenses"],
  },
  "fte-student": {
    term: "FTE student",
    short: "\"Full-time-equivalent\" student: part-time students are counted as a fraction of one, so FTE reflects total instructional workload rather than a head count. Graduate students are included, not just undergraduates.",
    long: "Finance figures per student (endowment, instruction spending) divide by FTE, not by undergraduate enrollment, so a university with many graduate students needs a larger endowment or budget to reach the same per-FTE figure.",
    category: "Cost & outcomes",
  },
  "ncaa-division": {
    term: "NCAA division",
    short: "The NCAA's three levels of college sports. Division I has the biggest athletic budgets and most athletic scholarships; Division II offers partial scholarships; Division III offers none, and athletes' aid comes the same way as other students'.",
    long: "Division I football splits in two: the Football Bowl Subdivision (FBS: the bowl games and the College Football Playoff) and the Football Championship Subdivision (FCS). The NAIA is a separate association of mostly smaller colleges, with its own scholarships and championships.",
    why: "It sets how big a part sports play in campus life, and whether athletic scholarships exist.",
    category: "School types",
    related: ["athletic-conference"],
  },
  "athletic-conference": {
    term: "Athletic conference",
    short: "The league a college's teams play in, such as the Big Ten or the Ivy League. A college can play football in one conference and its other sports in another.",
    why: "Conferences change as colleges realign, usually for TV money; a move can change travel, rivals, and a college's profile.",
    category: "School types",
    related: ["ncaa-division"],
  },
  rotc: {
    term: "ROTC",
    short: "Reserve Officers' Training Corps: military officer training alongside a regular degree, run by the Army, Navy (including the Marine Corps), or Air Force (including the Space Force). Scholarships pay tuition in exchange for service after graduation.",
    long: "A college listed here offers ROTC itself or through an arrangement with a nearby college; students may travel to another campus for some training.",
    category: "School types",
  },
  "study-abroad": {
    term: "Study abroad",
    short: "The college offers ways to earn credit while studying in another country, through its own programs or partners.",
    category: "School types",
  },
  "undergrad-research": {
    term: "Undergraduate research",
    short: "The college runs a program for undergraduates to do research with faculty, outside regular courses.",
    why: "Research experience helps with graduate school and some jobs. Many colleges offer it informally without listing a program.",
    category: "School types",
  },
  "academic-calendar": {
    term: "Academic calendar",
    short: "How the college divides the year: semesters (two terms), quarters (three terms plus an optional summer), trimesters, or 4-1-4 (two terms with a short January term between).",
    category: "School types",
  },
  "ap-credit": {
    term: "AP credit",
    short: "The college grants credit for Advanced Placement exams. Which scores count, and for which courses, varies by college and subject.",
    why: "Credit can let you skip introductory courses or graduate early; check each college's AP policy for the scores it accepts.",
    category: "Admissions",
  },
  "disability-services": {
    term: "Registered with disability services",
    short: "The share of undergraduates formally registered with the college's disability services office for accommodations. Colleges report the exact share only when it's over 3%.",
    why: "A higher share can mean an office that's easy to use, but it also depends on who enrolls; it isn't a rating of services.",
    category: "Students & access",
  },
  "housing-capacity": {
    term: "Housing capacity",
    short: "How many students the college can house in residence halls or other college-controlled housing, on or off campus.",
    long: "It's a count of beds, and at universities it can include housing for graduate students. So \"beds for every 100 undergrads\" is a rough guide, not a promise of a room.",
    category: "Cost & outcomes",
    related: ["live-on-requirement"],
  },
  "live-on-requirement": {
    term: "First-years must live on campus",
    short: "The college requires every full-time first-year to live in college housing, with no exceptions for commuters.",
    why: "Few colleges answer yes to the federal survey's strict version; many more require it with exceptions, such as for students living with family nearby.",
    category: "Cost & outcomes",
    related: ["housing-capacity"],
  },
  "application-fee": {
    term: "Application fee",
    short: "What the college charges to process an undergraduate application. Many colleges waive it for students who qualify.",
    category: "Admissions",
    related: ["applicants"],
  },
  "tuition-guarantee": {
    term: "Tuition guarantee",
    short: "A promise that the tuition rate a student starts at stays the same for a set time, usually four years.",
    why: "It makes the four-year cost easier to plan: the price you see in your first year is the price you keep.",
    category: "Cost & outcomes",
    related: ["promise-program"],
  },
  "promise-program": {
    term: "Promise program",
    short: "A state or local scholarship that covers tuition for residents who meet its rules, often graduates of local high schools.",
    why: "If you qualify, tuition at a participating college can cost little or nothing. Check your state's or city's program for the rules.",
    category: "Cost & outcomes",
    related: ["tuition-guarantee", "net-price"],
  },
  "federal-loan-rate": {
    term: "Share with a federal loan",
    short: "The share of all undergraduates who took out a federal student loan that school year. Private loans and parent PLUS loans aren't counted.",
    why: "Colleges with generous grants, or with \"no-loan\" aid policies, often have few students borrowing at all.",
    category: "Cost & outcomes",
    related: ["median-debt", "repayment-status"],
  },
  "repayment-status": {
    term: "Repayment status",
    short: "Where a college's former students stand on their federal loans three years after leaving: paid off, paying down, paused, not paying down, behind, or in default.",
    long: "\"Making progress\" means the balance is lower than when repayment began. \"Paused\" covers deferment and forbearance, when payments are officially put on hold. Some shares are published as a small range rather than an exact number, to protect privacy.",
    why: "It shows whether former students can actually pay back what they borrowed, which says something about both cost and outcomes.",
    category: "Cost & outcomes",
    related: ["in-default", "median-debt"],
  },
  "in-default": {
    term: "In default",
    short: "A federal student loan with no payment for about nine months. Default hurts credit and can lead to wages or tax refunds being taken.",
    category: "Cost & outcomes",
    related: ["repayment-status"],
  },
  "grant-aid": {
    term: "Grant aid",
    short: "Money for college that doesn't have to be repaid: federal, state, and local grants plus the college's own scholarships. Loans and work-study don't count.",
    category: "Cost & outcomes",
    related: ["net-price", "institutional-aid", "pell-grant"],
  },
  "institutional-aid": {
    term: "Institutional aid",
    short: "Grants and scholarships paid by the college itself, from its own budget or endowment. At wealthy private colleges this is usually the largest source of aid.",
    category: "Cost & outcomes",
    related: ["grant-aid", "need-based-aid", "merit-aid"],
  },
  "need-based-aid": {
    term: "Need-based aid",
    short: "Aid awarded because a family can't cover the full cost, based on financial information such as the FAFSA or CSS Profile.",
    category: "Cost & outcomes",
    related: ["need-met", "merit-aid"],
  },
  "merit-aid": {
    term: "Merit aid",
    short: "Scholarships awarded for academics, talent, or athletics regardless of financial need.",
    why: "Many highly selective colleges offer little or no merit aid; others use it heavily to attract students.",
    category: "Cost & outcomes",
    related: ["need-based-aid", "institutional-aid"],
  },
  "need-met": {
    term: "Percent of need met",
    short: "How much of a student's demonstrated financial need the college covers with aid, on average. 100% means the college fills the whole gap (though sometimes partly with loans).",
    category: "Cost & outcomes",
    related: ["need-based-aid"],
  },
  "federal-aid": {
    term: "Federal (Title IV) aid",
    short: "Federal grants, loans, and work-study, which require filing the FAFSA. Income-level breakdowns cover only students who received this aid.",
    why: "Families who don't file the FAFSA (often higher-income ones) aren't in those breakdowns.",
    category: "Cost & outcomes",
    related: ["pell-grant", "net-price-by-income"],
  },
  "net-price-calculator": {
    term: "Net price calculator",
    short: "A tool every college that takes federal aid must post on its website. Enter your family's finances to get a personalized estimate of what you'd pay.",
    why: "It's far more accurate for your family than any average on this site.",
    category: "Cost & outcomes",
    related: ["net-price"],
  },
  payback: {
    term: "Payback estimate",
    short: "Four years of average cost (all students) divided by median earnings 10 years after entry: roughly how many years of a typical salary the degree costs.",
    why: "It's a rough comparison tool. It ignores taxes, living costs, interest, and time to graduate, and your own costs and earnings will differ.",
    category: "How we measure",
    related: ["net-price", "median-earnings"],
  },
  public: {
    term: "Public",
    short: "A college funded partly by a state government. Usually cheaper for in-state residents.",
    category: "School types",
    related: ["private-nonprofit"],
  },
  "private-nonprofit": {
    term: "Private nonprofit",
    short: "A privately run college that reinvests revenue into the institution. Sticker prices are high, but aid is often generous.",
    category: "School types",
    related: ["public", "private-forprofit"],
  },
  "private-forprofit": {
    term: "Private for-profit",
    short: "A college run as a business for its owners or shareholders.",
    category: "School types",
    related: ["private-nonprofit"],
  },
  "percentile-rank": {
    term: "National rank",
    short: "Where a college falls among every 4-year college that reports that measure. \"Higher than 80%\" means it's above 80% of them.",
    why: "Colleges that don't report a measure (for example, test-blind schools and SAT scores) are left out of that comparison rather than counted as zero.",
    category: "How we measure",
    related: ["median"],
  },
  median: {
    term: "Median",
    short: "The middle value when everything is lined up in order: half of colleges are above it, half below. Less skewed by outliers than an average. Our medians cover every 4-year college that reports the measure.",
    category: "How we measure",
    related: ["percentile-rank"],
  },
  "inflation-adjusted": {
    term: "After inflation",
    short: "Past dollars converted to the latest year's dollars with the Consumer Price Index, so a change shows what's really more or less expensive, not just rising prices everywhere.",
    long: "We use CPI-U from the Bureau of Labor Statistics, averaged over each school year (July to June), the way the National Center for Education Statistics adjusts college prices.",
    why: "If a college's price rose 20% while prices across the economy rose 30%, it got cheaper in real terms. Switch charts to \"As reported\" to see the original dollars.",
    category: "How we measure",
    related: ["provisional-data"],
  },
  "provisional-data": {
    term: "Provisional data",
    short: "The newest year of a federal survey, before colleges' corrections are folded in. NCES publishes a revised version about a year later; values usually change little.",
    category: "How we measure",
    related: ["ipeds"],
  },
  "entering-cohort": {
    term: "Entering class",
    short: "Graduation rates follow the students who started in the same fall: \"entered fall\" years show the share of that class who finished within six years, measured six years later.",
    why: "A graduation rate always describes students who arrived years ago, so it moves slowly and lags changes a college makes today.",
    category: "How we measure",
    related: ["graduation-rate"],
  },
  "trend-direction": {
    term: "10-year direction",
    short: "Whether a college's cost, applications, diversity, and selectivity went up, held steady, or went down over its last 10 years of federal data.",
    long: "Cost is the average total cost after inflation; steady means within 5%. Applications count applicants; steady is within 10%. Diversity is the diversity index; steady is within 0.03. Selectivity follows the acceptance rate: a rate that fell by more than 3 percentage points means more selective. Applications and selectivity need at least 200 applicants at both ends. Diversity needs at least 300 undergrads at both ends, and is left out when the share of students whose race is unknown (counted with other groups) moved more than 10 points, since that is a change in reporting rather than in who enrolls.",
    why: "Up isn't good and down isn't bad: a rising cost after inflation means students pay more, while growing applications usually mean a college is in demand. Each indicator shows its number so you can judge the size of the change.",
    category: "How we measure",
    related: ["inflation-adjusted", "diversity-index", "selectivity"],
  },
  "trend-break": {
    term: "Break in a series",
    short: "A year when a measure's definition changed, so values before and after it aren't comparable. Charts stop the line there and don't report a change across it.",
    long: "The clearest case is the SAT: it was redesigned with a new scoring scale, so scores reported before the switch aren't comparable with scores after it.",
    category: "How we measure",
    related: ["sat"],
  },
  "fixed-panel": {
    term: "Fixed panel",
    short: "A national trend measured over the same colleges in every year: only those that report both the first and last year. Otherwise colleges opening, closing, or starting to report would look like change.",
    category: "How we measure",
    related: ["median"],
  },
  "colleges-or-students": {
    term: "Colleges or students",
    short: "A share of colleges counts each college once and answers \"how common is this?\". A students figure weights each college by its size and answers \"how many people does this affect?\". Each national trend chart says which one it shows.",
    long: "The two can tell different stories: a change at many small colleges moves the share of colleges a lot and the students figure a little, and one large university can move the students figure on its own.",
    category: "How we measure",
    related: ["fixed-panel", "median"],
  },
  "todays-classification": {
    term: "Today's classification",
    short: "National trend studies group each college by what it is today (its region, size, selectivity, and so on) at every point in the line. A college that grew past 10,000 undergraduates counts as 10,000+ throughout.",
    why: "It keeps each group the same colleges from start to finish, but a group's change can partly reflect which colleges ended up in it.",
    category: "How we measure",
    related: ["fixed-panel"],
  },
  "conference-membership": {
    term: "Today's members or members at the time",
    short: "A conference's line over time can follow its members today in every year (the default), or whoever was a member that year. Today's members describe the same colleges throughout; members at the time describe the conference as it was, so a jump can come from who joined.",
    why: "Conferences realign. When several colleges join at once, a median can change because the membership changed, not because any college did.",
    category: "How we measure",
    related: ["athletic-conference", "todays-classification"],
  },
  "too-few-colleges": {
    term: "Too few colleges to say",
    short: "A group needs at least 30 colleges in a study's panel before it gets a number (10 for a state, 8 for an athletic conference). Below that, a few colleges can swing a share or median, so the group shows its count only.",
    category: "How we measure",
    related: ["fixed-panel", "median"],
  },
  "biggest-movers": {
    term: "Biggest movers",
    short: "Ten colleges per measure that changed the most over the window, among colleges that cleared a size floor at its start. Colleges under 300 undergraduates today, closed or merged campuses, and figures that jumped more than threefold in a year are left out; growth lists also leave out online-first and for-profit colleges.",
    why: "A percent change on a small base, a merger, or a typo in one year's report can top a naive list. The rules keep the lists to real campuses that really changed.",
    category: "How we measure",
    related: ["percentage-points", "fixed-panel", "inflation-adjusted"],
  },
  "percentage-points": {
    term: "Percentage points",
    short: "The difference between two percentages: an acceptance rate going from 60% to 40% fell 20 points (a third of its value, or 33%). Changes in rates and shares are shown in points.",
    category: "How we measure",
    related: ["biggest-movers"],
  },
  "online-first": {
    term: "Online-first college",
    short: "A college where more than half of undergraduates take all their courses online (IPEDS distance-education counts). Its enrollment can grow without a campus growing, so growth lists leave it out.",
    category: "How we measure",
    related: ["biggest-movers"],
  },
  ipeds: {
    term: "IPEDS",
    short: "The Integrated Postsecondary Education Data System: annual surveys every federally funded U.S. college must complete.",
    category: "Data sources",
    related: ["scorecard", "cds"],
  },
  scorecard: {
    term: "College Scorecard",
    short: "The U.S. Department of Education's public dataset and API covering costs, admissions, and outcomes for U.S. colleges.",
    category: "Data sources",
    related: ["ipeds"],
  },
  cds: {
    term: "Common Data Set",
    short: "A standardized survey colleges publish voluntarily, with detailed admissions, enrollment, and aid statistics.",
    category: "Data sources",
    related: ["ipeds"],
  },
  // CDS C8/C9 (specs/data-expansion/cds-test-scores-and-policy.md).
  "score-bands": {
    term: "Score bands",
    short: "The share of enrolled first-years who sent a test whose score fell in each range, such as SAT 1400–1600 or ACT 30–36, from the college's Common Data Set.",
    why: "Bands show how scores spread across the whole class, not just the middle half. They describe only students who sent scores.",
    category: "Test scores",
    related: ["middle-50", "test-submission", "sat", "act"],
  },
  "application-cycle": {
    term: "Application cycle",
    short: "The year students apply, named by the fall they would enroll. A college's Common Data Set states its test policy for the coming cycle.",
    category: "Admissions",
    related: ["test-policy"],
  },
  "required-for-some": {
    term: "Required for some applicants",
    short: "A test policy where some applicants (for example, those to certain programs) must send SAT or ACT scores and others needn't. Only a college's Common Data Set reports it.",
    category: "Test scores",
    related: ["test-policy", "test-optional"],
  },
  region: {
    term: "Region",
    short: "The part of the country a school is in: Northeast, Southeast, Midwest, Southwest, or West.",
    category: "School types",
  },
  // CDS admissions by residency (specs/data-expansion/cds-residency-admissions.md).
  "admit-rate-by-residency": {
    term: "Acceptance rate by residency",
    short: "The share of applicants from the college's own state who were admitted, and the same for applicants from other states and from abroad, as the college reports them in its Common Data Set.",
    long: "Residency is where an applicant lived when applying, which isn't always the same as qualifying for in-state tuition. This is different from the share of first-years who come from out of state: that counts who enrolled, this counts who got in.",
    why: "At many public universities in-state applicants are admitted at a higher rate, but not everywhere, and some private colleges show the opposite. A group's rate also depends on who applies from there.",
    category: "Admissions",
    related: ["acceptance-rate", "in-state-student", "yield-by-residency"],
  },
  "yield-by-residency": {
    term: "Yield by residency",
    short: "Of the students admitted from each place, the share who enrolled.",
    category: "Admissions",
    related: ["yield", "admit-rate-by-residency"],
  },
  // CDS cost and debt (specs/data-expansion/cds-cost-and-debt.md).
  "next-year-price": {
    term: "Next year's price",
    short:
      "Tuition, required fees, and on-campus food and housing for the coming academic year, as the college published them in its Common Data Set, before any aid.",
    long: "Federal prices describe a year that has already happened and arrive a year or more late, so this is shown beside the federal price rather than replacing it. It isn't used in rankings or comparisons, and it doesn't include books, transportation, or personal expenses.",
    why: "It tells you roughly what the next entering class will be charged, and how fast the price is rising.",
    category: "Cost & outcomes",
    related: ["cost-of-attendance", "net-price"],
  },
  "cumulative-principal": {
    term: "Average total borrowed (all loan types)",
    short:
      "From the college's Common Data Set: the average total a graduating class's borrowers took out over their whole degree, counting federal, institutional, state, and private loans.",
    long: "The federal median debt beside it counts only federal loans, uses the middle borrower rather than the average, and includes students who left without a degree, so the two figures differ by design. Only students who started at the college as first-time students and earned a bachelor's are counted. Interest isn't included.",
    why: "Private loans often carry higher rates and fewer protections than federal ones, and federal data leaves them out.",
    category: "Cost & outcomes",
    related: ["median-debt", "federal-loan-rate"],
  },
  // CDS admissions profile (specs/data-expansion/cds-admissions.md).
  "high-school-gpa": {
    term: "High school GPA",
    short: "First-years' grade-point averages from high school, as the college reports them in its Common Data Set: an average, and the share in each GPA band.",
    long: "These describe students who enrolled, not everyone admitted. The bands use a 4.0 scale; the average may be weighted, and only counts the first-years who reported a GPA.",
    why: "It shows where a typical first-year's grades fell, but high schools grade differently, so compare a college only with itself.",
    category: "Admissions",
    related: ["weighted-gpa", "gpa-band", "class-rank"],
  },
  "weighted-gpa": {
    term: "Weighted GPA",
    short: "A GPA that gives extra points for honors, AP, or IB courses, so it can run above 4.0. It can't be compared with an unweighted GPA on a 4.0 scale.",
    category: "Admissions",
    related: ["high-school-gpa"],
  },
  "gpa-band": {
    term: "GPA band",
    short: "A range of high school GPAs (4.0, 3.75–3.99, 3.50–3.74, and so on) and the share of first-years whose GPA fell in it, on a 4.0 scale.",
    long: "At colleges whose average is weighted, the top \"4.0\" band seems to hold every GPA of 4.0 or more.",
    category: "Admissions",
    related: ["high-school-gpa"],
  },
  "class-rank": {
    term: "Class rank",
    short: "Where a student stood in their high school class (top tenth, top quarter, top half). Many high schools no longer rank, so these shares describe only the first-years whose school reported one.",
    category: "Admissions",
    related: ["high-school-gpa"],
  },
  "factor-importance": {
    term: "How much each factor counts",
    short: "In its Common Data Set, a college marks each part of an application as very important, important, considered, or not considered when it decides whom to admit.",
    long: "\"Very important\" parts weigh most; \"considered\" parts can help but weigh less; \"not considered\" parts aren't used, even if you send them. The federal survey asks a simpler question (required, considered, or not considered).",
    category: "Admissions",
    related: ["admission-factor", "legacy-status"],
  },
  "religious-affiliation": {
    term: "Religious affiliation",
    short: "The church or faith a college says it's affiliated with in its federal report, such as Roman Catholic or United Methodist. Public colleges and many private ones have none.",
    long: "Colleges report one affiliation from a federal list of about 60 to the Integrated Postsecondary Education Data System (IPEDS) each year, and we show the federal label as written. Explore groups them into broader families (Catholic, Baptist, Lutheran, and so on). Affiliation alone says little about daily campus life: some affiliated colleges are deeply religious and others keep only a historical tie.",
    why: "It's a starting point. The college's own answers, such as how much religious commitment counts in admission, say more about how faith shapes the campus.",
    category: "Students & access",
    related: ["religious-commitment", "faith-centered", "campus-ministries"],
  },
  "religious-commitment": {
    term: "Religious commitment in admissions",
    short: "In its Common Data Set, a college marks how much an applicant's religious affiliation or commitment counts when it decides whom to admit: very important, important, considered, or not considered.",
    long: "Most colleges, including most religiously affiliated ones, mark it not considered. A college that marks it very important usually expects students to share or support its faith.",
    category: "Admissions",
    related: ["factor-importance", "religious-affiliation", "faith-centered"],
  },
  "religious-scholarships": {
    term: "Scholarships for religious affiliation",
    short: "In its Common Data Set, a college marks the things its own scholarships consider. This one means some of its aid goes to students of a particular faith or church, need-based, non-need-based, or both.",
    long: "An unmarked box isn't a \"no\": colleges often leave the list partly blank.",
    category: "Cost & outcomes",
    related: ["religious-affiliation", "merit-aid"],
  },
  "campus-ministries": {
    term: "Campus ministries",
    short: "Religious groups or a chaplaincy serving students on campus, as the college lists them among its activities in its Common Data Set.",
    long: "A checked box says the college has some; it doesn't say which faiths or how many students take part. Public colleges often have student-run ministries even though they have no religious affiliation.",
    category: "Students & access",
    related: ["religious-affiliation"],
  },
  "national-directory": {
    term: "Listed by a national organization",
    short: "A national organization's own list of its campus chapters or groups, matched to this college. Each listing names who published the list and when we read it.",
    long: "It is the organization's claim, not confirmed by the college, and lists can lag behind a chapter that opened or closed. We match each entry to a college by name, city, and state, and leave out any we can't match with confidence.",
    category: "Students & access",
    related: ["campus-ministries", "hillel-chabad", "newman-center"],
  },
  "hillel-chabad": {
    term: "Hillel and Chabad",
    short: "The two national organizations most campus Jewish communities belong to. Hillel is a campus student organization; Chabad on Campus (often called a Chabad House) is a rabbi-led house near campus, part of the worldwide Chabad-Lubavitch movement.",
    long: "A college can have one, both, or neither. We show presence from each organization's own list of its campus chapters or centers, not a shared headcount.",
    category: "Students & access",
    related: ["national-directory"],
  },
  "newman-center": {
    term: "Newman Center",
    short: "A Catholic campus ministry center, often named for Cardinal John Henry Newman. FOCUS (Fellowship of Catholic University Students) is the largest national organization placing missionaries on campuses; a college can have a Newman Center, FOCUS, both, or neither.",
    category: "Students & access",
    related: ["national-directory", "campus-ministries"],
  },
  "faith-centered": {
    term: "Faith-centered",
    short: "The college's own Common Data Set says religious affiliation or commitment is very important in admission, or the college is a full (voting) member of the Council for Christian Colleges & Universities (CCCU). We never use the label for an affiliation alone.",
    category: "Students & access",
    related: ["religious-commitment", "religious-affiliation"],
  },
  "early-decision": {
    term: "Early decision",
    short: "An early application that is binding: if admitted, you commit to enroll and withdraw your other applications. Decisions usually come in December.",
    long: "Some colleges run a second round (ED II) with a later deadline. Recruited athletes and other applicants with an edge often apply early, so a college's early admit rate overstates the gain for a typical applicant.",
    category: "Admissions",
    related: ["early-action", "restrictive-early-action"],
  },
  "early-action": {
    term: "Early action",
    short: "An early application that isn't binding: you hear back early but can still choose another college by the usual May 1 deadline.",
    category: "Admissions",
    related: ["early-decision", "restrictive-early-action"],
  },
  "restrictive-early-action": {
    term: "Restrictive early action",
    short: "Non-binding early action where you agree not to apply early to other colleges' early plans, with exceptions the college sets. Also called single-choice early action.",
    category: "Admissions",
    related: ["early-action", "early-decision"],
  },
  "wait-list": {
    term: "Wait list",
    short: "A list of qualified applicants a college may admit later if spaces open. Applicants choose whether to accept a place on it; at many colleges few are admitted from it.",
    category: "Admissions",
    related: ["admitted", "yield"],
  },
  // CDS financial aid (specs/data-expansion/cds-financial-aid.md).
  "css-profile": {
    term: "CSS Profile",
    short: "A financial aid form from the College Board that many private colleges require on top of the FAFSA. It asks more than the FAFSA does (home equity, a business, both parents' finances) so the college can award its own grants.",
    long: "The FAFSA decides federal aid such as Pell Grants. Colleges that give a lot of their own money often want the fuller picture the CSS Profile gives, and use it with their own formula for need. It has a fee, with waivers for lower-income families.",
    why: "If a college you're applying to requires it, its deadline is usually earlier than the FAFSA's and missing it can cost you the college's own grants.",
    category: "Cost & outcomes",
    related: ["noncustodial-profile", "aid-methodology", "need-based-aid"],
  },
  "noncustodial-profile": {
    term: "CSS Noncustodial Profile",
    short: "A second CSS Profile filed by the parent a student doesn't live with, when parents are divorced or separated. Colleges that require it count that parent's income and assets in figuring need.",
    category: "Cost & outcomes",
    related: ["css-profile"],
  },
  "business-farm-supplement": {
    term: "Business/Farm Supplement",
    short: "An extra form some colleges ask of families who own a business or farm, so they can judge what it's worth and what it earns before awarding their own aid.",
    category: "Cost & outcomes",
    related: ["css-profile"],
  },
  "aid-methodology": {
    term: "Need methodology (federal or institutional)",
    short: "How a college works out what a family can pay. The federal formula uses the FAFSA alone; a college's own (institutional) formula usually adds the CSS Profile and can count home equity or a noncustodial parent. The same family can show different need at two colleges.",
    category: "Cost & outcomes",
    related: ["css-profile", "need-met", "need-based-aid"],
  },
  "aid-package": {
    term: "Aid package",
    short: "Everything a college offers a student with need: grants and scholarships, plus self-help (loans and work-study). The Common Data Set's average package leaves out loans meant to replace the family's contribution (parent PLUS, unsubsidized, private loans).",
    category: "Cost & outcomes",
    related: ["self-help-aid", "need-based-aid"],
  },
  "self-help-aid": {
    term: "Self-help aid",
    short: "Aid a student pays back or works for: student loans and work-study jobs, as opposed to grants and scholarships, which are free money.",
    category: "Cost & outcomes",
    related: ["aid-package"],
  },
  "merit-dollar-share": {
    term: "College grant dollars given as merit",
    short: "Of the grant money a college gives from its own funds, the share awarded without regard to need. Merit money that went toward a student's need counts as need-based in the Common Data Set, so this is merit beyond need.",
    category: "Cost & outcomes",
    related: ["merit-aid", "institutional-aid"],
  },
  "athletic-scholarship": {
    term: "Athletic scholarship",
    short: "Aid a college gives for playing a sport, regardless of need. NCAA Division III colleges don't give them; Division I and II colleges and NAIA members can.",
    category: "Cost & outcomes",
    related: ["merit-aid", "ncaa-division"],
  },
  "aid-for-international-students": {
    term: "Aid for international students",
    short: "Grants a college gives from its own funds to students who aren't U.S. citizens or permanent residents. They can't get federal aid, so the college's own aid is usually all there is. Federal data doesn't track it; this comes from the college's Common Data Set.",
    category: "Cost & outcomes",
    related: ["institutional-aid", "css-profile"],
  },
  // CDS academics (specs/data-expansion/cds-academics.md). Definitions quoted from the Common Data Set's own sheet.
  "cds-student-faculty-ratio": {
    term: "Student-to-faculty ratio (Common Data Set)",
    short:
      "The college's own ratio from its Common Data Set: full-time-equivalent undergraduate and graduate students (full-time plus 1/3 part-time) to full-time-equivalent instructional faculty, leaving out stand-alone graduate or professional programs such as medicine, law, or business.",
    long:
      "The Common Data Set's definition: \"the ratio of full-time equivalent undergraduate and graduate students (full-time plus 1/3 part time) to full-time equivalent instructional faculty of undergraduate and graduate students (full-time plus 1/3 part time). In the ratio calculations, exclude both faculty and students in stand-alone graduate or professional programs such as medicine, law, veterinary, dentistry, social work, business, or public health in which faculty teach virtually only graduate level students.\" It is a different number than the federal ratio shown elsewhere on this page, because the two are defined differently, not because one is wrong.",
    why: "Two honest numbers can differ: Harvard reports 11 to 1 in its Common Data Set and 7 to 1 to the federal survey.",
    category: "Students & access",
    related: ["student-faculty-ratio", "class-section"],
  },
  "class-section": {
    term: "Class section",
    short:
      "One meeting of a credit course at a stated time, not a lab or discussion subsection, with at least one degree-seeking undergraduate enrolled. Class sizes count sections, not students.",
    long:
      "The Common Data Set's definition: \"an organized course offered for credit, identified by discipline and number, meeting at a stated time or times in a classroom or similar setting, and not a subsection such as a laboratory or discussion session.\" Distance-learning and noncredit classes, independent study, internships, and one-on-one instruction are left out. Because a lecture of 300 is one section, a student is more likely to sit in a large class than the share of sections suggests.",
    why: "The closest published answer to \"how big are my classes?\", if you keep in mind that it counts sections, not seats.",
    category: "Students & access",
    related: ["class-subsection", "student-faculty-ratio"],
  },
  "class-subsection": {
    term: "Class subsection",
    short: "A lab, recitation, or discussion that meets separately from a course's lecture. The Common Data Set counts these apart from class sections.",
    long:
      "The Common Data Set's definition: \"any subsection of a course, such as laboratory, recitation, and discussion subsections that are supplementary in nature and are scheduled to meet separately from the lecture portion.\" Like sections, they are counted per meeting group, not per student.",
    category: "Students & access",
    related: ["class-section"],
  },
  "open-curriculum": {
    term: "Open curriculum",
    short: "The college reports no college-wide required coursework: students choose their own classes outside their major.",
    long: "Shown when a college's Common Data Set lists special study options but checks none of the required-coursework areas. Majors still have their own requirements, and some colleges with an open curriculum ask for a writing course or a spread of subjects in other ways.",
    why: "Freedom to explore, with more responsibility for building a broad education yourself.",
    category: "Students & access",
    related: ["required-core"],
  },
  "required-core": {
    term: "Required coursework",
    short: "Subject areas every undergraduate must take courses in, whatever their major, as the college lists them in its Common Data Set.",
    long: "A college checks each area it requires (English composition, math, sciences, a foreign language, and so on). An area that isn't listed may still be required by some programs, or the college may simply not have checked the box.",
    category: "Students & access",
    related: ["open-curriculum"],
  },
  // CDS transfer admission (specs/data-expansion/cds-transfer.md).
  "transfer-admission": {
    term: "Transfer admission",
    short: "How many students applied to transfer in from another college, how many were admitted, and how many enrolled, as the college reports them in its Common Data Set. The transfer acceptance rate is admitted ÷ applied.",
    long: "This is the transfer funnel, so it counts who got in. The federal count of new transfer students is a different measure: it counts every transfer student who enrolled that fall, however they were admitted, and comes from a different survey, so the two numbers rarely match exactly. The college's Common Data Set also lists the terms transfers may start, the minimum credits to apply, and what the application needs.",
    why: "A college that admits few first-year applicants may admit transfers at a very different rate, higher or lower, and some colleges take transfers only in the fall.",
    category: "Admissions",
    related: ["transfer-in", "acceptance-rate", "advanced-standing"],
  },
  "advanced-standing": {
    term: "Advanced standing",
    short: "Credit a transfer student gets for courses already completed at another college, so they don't start over as a first-year.",
    long: "Colleges say in their Common Data Set whether transfers can earn it. How many credits count, and for which courses, varies by college and program.",
    category: "Admissions",
    related: ["transfer-admission", "transfer-in"],
  },
  // CDS application logistics and high school preparation (specs/data-expansion/cds-application-logistics.md).
  "priority-date": {
    term: "Priority date",
    short: "An earlier date some colleges set before the regular deadline. Applying by it can matter for scholarships, honors programs, or housing, even though applications are still accepted afterwards.",
    why: "Missing a priority date usually doesn't rule you out, but it can cost you a chance at money or a place in a program that fills first.",
    category: "Admissions",
    related: ["reply-by-date"],
  },
  "rolling-notification": {
    term: "Rolling notification",
    short: "The college sends decisions as it finishes reading applications, starting on a set date, rather than all on one day.",
    why: "Applying early in a rolling cycle usually means hearing back sooner.",
    category: "Admissions",
    related: ["reply-by-date"],
  },
  "reply-by-date": {
    term: "Reply-by date",
    short: "The date by which an admitted student must accept or decline the offer, usually with a deposit. Many colleges use May 1, or a few weeks after the decision for students admitted later.",
    category: "Admissions",
    related: ["housing-deposit", "rolling-notification"],
  },
  "housing-deposit": {
    term: "Housing deposit",
    short: "Money an admitted student pays to hold a place in campus housing, with its own deadline. The college's Common Data Set says whether it's refunded if you don't enroll.",
    category: "Cost & outcomes",
    related: ["reply-by-date"],
  },
  "deferred-admission": {
    term: "Deferred admission (gap year)",
    short: "Postponing enrollment after being admitted, for example to take a gap year, with the college holding your place for a set time.",
    long: "Not the same as being deferred in early decision or early action, where the college moves your application to the regular round without deciding yet. Deferred admission comes after you're admitted.",
    category: "Admissions",
    related: ["reply-by-date"],
  },
  "college-preparatory-program": {
    term: "College-preparatory program",
    short: "A high school course plan built around academic subjects: English, math, science, a foreign language, and social studies. A college's Common Data Set says whether it requires one, recommends one, or neither, and how many years (units) of each subject it expects.",
    long: "A unit is one year of a subject. Lab science units are part of the science count, not extra.",
    category: "Admissions",
  },
  // CDS Greek life, phase 1 (specs/greek-life.md; lib/cds/greek.ts).
  "greek-life": {
    term: "Fraternity / sorority participation",
    short: "The share of undergraduate men in a fraternity and women in a sorority, as the college reports them separately in its Common Data Set. The two percentages are never added together.",
    long: "Each percentage is reported for first-year students and for all undergraduates; a blank means the college didn't answer, not 0%. The mark on each bar is the median among the colleges whose Common Data Set we've read that report it, so it covers a small, growing set of colleges. Housing is reported separately (whether the college offers fraternity or sorority housing) and doesn't imply a participation rate, or the reverse.",
    why: "How big a part Greek organizations play varies enormously by college, from none to a majority of students, and the two sides (fraternities, sororities) can differ a lot at the same college.",
    category: "School types",
  },
  // Greek life, phase 4: national chapter directories by council (specs/greek-life.md, specs/campus-directories.md).
  npc: {
    term: "Panhellenic (NPC)",
    short: "The National Panhellenic Conference, the umbrella of 26 historically white sororities. A college's \"Panhellenic\" council is usually its NPC chapters.",
    long: "NPC's own campus-level chapter data is kept behind a member login, so what's shown here (when shown) comes from each sorority's own public chapter list, credited by name.",
    category: "Students & access",
    related: ["greek-life", "national-directory"],
  },
  nic: {
    term: "Interfraternity (IFC / NIC)",
    short: "Most historically white fraternities belong to the North American Interfraternity Conference (NIC); a college's own Interfraternity Council (IFC) is usually its NIC chapters.",
    long: "Like NPC, NIC's own campus-level chapter data is kept behind a member login; this site reads each fraternity's own public chapter list instead.",
    category: "Students & access",
    related: ["greek-life", "national-directory"],
  },
  nphc: {
    term: "NPHC (the \"Divine Nine\")",
    short: "The National Pan-Hellenic Council, the umbrella of nine historically Black fraternities and sororities, often called the Divine Nine.",
    category: "Students & access",
    related: ["greek-life", "national-directory"],
  },
  nalfo: {
    term: "NALFO (Latino fraternities and sororities)",
    short: "The National Association of Latino Fraternal Organizations, an umbrella of fraternities and sororities founded by and for Latino students.",
    category: "Students & access",
    related: ["greek-life", "national-directory"],
  },
  napa: {
    term: "NAPA (Asian-interest fraternities and sororities)",
    short: "The National APIDA Panhellenic Association, an umbrella of fraternities and sororities founded by and for Asian American and Pacific Islander Desi American students.",
    category: "Students & access",
    related: ["greek-life", "national-directory"],
  },
  nmgc: {
    term: "NMGC (multicultural fraternities and sororities)",
    short: "The National Multicultural Greek Council, an umbrella of fraternities and sororities founded around a shared multicultural or affinity identity other than NPC, NIC, NPHC, NALFO, or NAPA's.",
    category: "Students & access",
    related: ["greek-life", "national-directory"],
  },
  colony: {
    term: "Colony",
    short: "A group a national fraternity or sorority is building toward a full chapter, usually with fewer members and without a chapter's full voting rights yet. Chapter directories flag colonies separately from active chapters.",
    category: "Students & access",
    related: ["greek-life", "national-directory"],
  },
  // Campus-life pilot (lib/campus-pages.ts): facts read from a college's own pages, each quoted and dated.
  "college-page-fact": {
    term: "From the college's own page",
    short: "A fact read on the college's own website (a policy page, an office's page, or a report), with the page's own words and the date we checked it.",
    long: "Facts older than two years are hidden until they're checked again. A finding that a policy is missing, a conduct-code restriction, or an official religious breakdown is published only after a second, independent model check confirms it against the quote and the page.",
    category: "Students & access",
    related: ["national-directory"],
  },
  "greek-council": {
    term: "Fraternity and sorority councils",
    short: "The governing groups a college's fraternities and sororities belong to, such as the Panhellenic Council (sororities), the Interfraternity Council, and the National Pan-Hellenic Council (historically Black organizations).",
    long: "Member counts come from the college's fraternity and sorority life office and describe one term; spring counts usually run lower than fall. Counts under 10 show as \"fewer than 10\".",
    category: "School types",
    related: ["greek-life"],
  },
  "deferred-recruitment": {
    term: "Deferred recruitment",
    short: "First-year students can't join a fraternity or sorority in their first term; recruitment for them waits until a later term.",
    category: "School types",
    related: ["greek-life"],
  },
  "religious-composition": {
    term: "Students by religious affiliation",
    short: "The religions students report, as the college itself publishes them (usually in an institutional-research report). Few colleges publish one, mostly religious colleges.",
    long: "Students choose whether to answer, so \"not specified\" can be large. The figures describe the students and year the college names.",
    category: "Students & access",
    related: ["religious-affiliation"],
  },
  "lgbtq-policies": {
    term: "LGBTQ+ policies on the college's pages",
    short: "Whether the college's own pages say its nondiscrimination policy covers sexual orientation and gender identity, and whether it offers gender-inclusive housing, chosen names on records, an all-gender restroom list, and student health coverage of transition-related care.",
    long: "Each item links the page and the date it was checked. \"Not found\" items aren't shown: a missing page is not a no. A \"no\" appears only where a page says so, confirmed by a second model check.",
    category: "Students & access",
    related: ["another-gender"],
  },
  "conduct-code-restriction": {
    term: "What the student conduct policy says",
    short: "The college's own words, quoted, where its conduct code, honor code, or community covenant restricts same-sex relationships, gender expression, or transition.",
    long: "Shown only from the college's current document, never inferred from a religious affiliation, and only after a second model check confirms the quote and its meaning.",
    category: "Students & access",
    related: ["religious-affiliation"],
  },
} satisfies Record<string, GlossaryEntry>;

export type TermKey = keyof typeof entries;

export const GLOSSARY: Record<TermKey, GlossaryEntry> = entries;

export function isTermKey(key: string): key is TermKey {
  return key in GLOSSARY;
}

export function termsByCategory(): { category: GlossaryCategory; terms: [TermKey, GlossaryEntry][] }[] {
  return GLOSSARY_CATEGORIES.map((category) => ({
    category,
    terms: (Object.entries(GLOSSARY) as [TermKey, GlossaryEntry][])
      .filter(([, e]) => e.category === category)
      .sort((a, b) => a[1].term.localeCompare(b[1].term)),
  }));
}
